# Generated by Django 4.1.5 on 2023-02-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0003_alter_borrowing_actual_return_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowing",
            name="return_status",
            field=models.BooleanField(default=False),
        ),
    ]
