# Generated by Django 4.1.5 on 2023-02-19 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0004_borrowing_return_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrowing",
            old_name="book_id",
            new_name="book",
        ),
        migrations.RenameField(
            model_name="borrowing",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="borrowing",
            name="return_status",
        ),
    ]
