# Generated by Django 4.1.5 on 2023-02-16 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_user_payments_payment_payments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="payments",
        ),
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
